### ISSUE TITLE
Do we need to mention objective-c in the style guide?

### ISSUE THREAD

**Issue by zummenix** [Saritasa/ios-development-guides#5]
All current projects are started in swift.

**Comment by akhatmullin** [comment]
I think we should mention objective-c in style guide a little bit.
For example about using literals:
`@123` instead of `[NSNumber numberWithInt:123]`
`@(someFloatValue)` instead of `[NSNumber numberWithFloat:someFloatValue]`
`@{key: value}` instead of `[NSDictionary dictionaryWithObjectsAndKeys: value, key, nil]`
`@[object1, object2, object3]` instead of `[NSArray arrayWithObjects:object1, object2, object3, nil]`

**Comment by zummenix** [comment]
Yeah, good point.
